//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKBarsMedApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalECP
    {
        public int id_ecp { get; set; }
        public string NumberECP { get; set; }
        public string Sender { get; set; }
        public Nullable<System.DateTime> DateReceipt { get; set; }
        public int id_employee { get; set; }
        public Nullable<System.DateTime> DateConnect { get; set; }
        public int id_tecsupemp { get; set; }
        public string HardwareNum { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TechnicalSupEmployee TechnicalSupEmployee { get; set; }
    }
}
